#!/usr/bin/python3

import sys
import http.server
import socketserver
import threading
import socket
import time
import requests

PORT = 8113
DIRECTORY = "build"

httpd = None


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)


def start_server():
    httpd.serve_forever()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Argument 1 needs to be the IP of the device")
        sys.exit(1)
    destination_ip = sys.argv[1]

    httpd = socketserver.TCPServer(("", PORT), Handler)
    t = threading.Thread(target=httpd.serve_forever)
    t.start()

    x = requests.post(
        url=f"http://{destination_ip}/jsonrpc",
        data='{"jsonrpc": "2.0", "method": "ota", "params": {"upgrade_url": "http://192.168.1.3:8113/dwn.bin"}, "id": "1"}',
    )
