#!/usr/bin/python3

import sys
import http.server
import socketserver
import threading
import socket
import time
PORT = 8113
DIRECTORY = "build"

httpd = None

class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)


def start_server():
    httpd.serve_forever()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Argument 1 needs to be the IP of the device");
        sys.exit(1)
    destination_ip = sys.argv[1] 

    httpd = socketserver.TCPServer(("", PORT), Handler)
    t = threading.Thread(target=httpd.serve_forever)
    t.start()

    time.sleep(0.5)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) # UDP
    sock.sendto(bytes("start download", "utf-8"), (destination_ip, 242)) 

