#pragma once
#include <esp_event_base.h>

#define MAX_URIS 15
#define DEFAULT_SCAN_LIST_SIZE 10
#define GPIO_OUTPUT_LED 13
#define GPIO_INPUT_PROV_WAP 4
#define PIN_POLL_SLEEP 200
#define TASKPOOL_SIZE 5
#define MAX_WS_CLIENTS 5

ESP_EVENT_DECLARE_BASE(GPIO_EVENT);
ESP_EVENT_DECLARE_BASE(PROV_EVENT);

#define GPIO_UP 1
#define GPIO_DOWN 2